baseURL = "https://www.duffymogstudios.ie/"
languageCode = "en-ie"
title = "Duffymog Studios"

[params]
  description = "Wedding Photographer Dublin & Ireland"

[markup.goldmark.renderer]
  unsafe = true
