baseURL = "https://www.duffymogstudios.ie/"
languageCode = "en-ie"
title = "Duffymog Studios"

[params]
  description = "Wedding Photographer Dublin & Ireland"

[imaging]
  quality = 90

[imaging.exif]
  disableLatLong = true

[markup.goldmark.renderer]
  unsafe = true
