baseURL = "https://www.duffymogstudios.ie/"
languageCode = "en-ie"
title = "Duffymog Studios"

[params]
  description = "Wedding & Family Photographer Dublin & Ireland"
  # phone = "+353XXXXXXXXX"  # Set this to enable telephone in LocalBusiness schema
  googleRatingValue = 5.0
  googleReviewCount = 29

disableKinds = ["taxonomy", "term"]

[imaging]
  quality = 80

[imaging.exif]
  disableLatLong = true

[markup.goldmark.renderer]
  unsafe = true
